# Generated by Django 2.1.1 on 2018-09-17 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='전술 인형 넘버링')),
                ('rank', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='전술 인형 등급')),
                ('type', models.CharField(choices=[('hg', 'hg'), ('ar', 'ar'), ('smg', 'smg'), ('sg', 'sg'), ('mg', 'mg'), ('rf', 'rf')], max_length=3, verbose_name='전술 인형 타입')),
                ('buildtime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='전술 인형 제조 시간')),
                ('codename', models.CharField(blank=True, max_length=50, null=True, verbose_name='전술 인형 명칭')),
                ('grow', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill01_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill01_codename', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill01_cooldowntype', models.CharField(blank=True, choices=[('frame', 'frame'), ('turn', 'turn')], max_length=4, null=True)),
                ('skill01_initialcooldown', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill01_consumption', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill02_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill02_codename', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill02_cooldowntype', models.CharField(blank=True, choices=[('frame', 'frame'), ('turn', 'turn')], max_length=4, null=True)),
                ('skill02_initialcooldown', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill02_consumption', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('obtain', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('equip01', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('equip02', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('equip03', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('mindupdata', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('is_upgrade', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DollDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_field', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Drop Fields')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_drop', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effecttype', models.CharField(blank=True, max_length=100, null=True)),
                ('effectcenter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effectpos', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_effect', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollEffectGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pow', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dodge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criticalpercent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('colldown', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('armor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_effect_grid', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSDImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_sd_wait_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 기본 일러스트')),
                ('doll_sd_attack_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 공격 일러스트')),
                ('doll_sd_die_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 파손 일러스트')),
                ('doll_sd_move_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 이동 일러스트')),
                ('doll_sd_victory1_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 승리1 일러스트')),
                ('doll_sd_victory2_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 승리2 일러스트')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_sd', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSkill01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooldown', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_skill_data01', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSkill02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooldown', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_skill_data02', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSkinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_name', models.CharField(blank=True, max_length=50, verbose_name='스킨 이름')),
                ('default_skin', models.ImageField(blank=True, upload_to='doll_default_skins', verbose_name='스킨 기본 일러스트')),
                ('damage_skin', models.ImageField(blank=True, upload_to='doll_damage_skins', verbose_name='스킨 파손 일러트스')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_skins', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pow', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dodge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('armorpiercing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criticalpercent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bullet', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doll_status', to='tactical_dolls.Doll')),
            ],
        ),
    ]
