# Generated by Django 2.1.1 on 2018-09-14 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('doll_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='인형 품번')),
                ('name', models.CharField(max_length=50, verbose_name='인형 이름')),
                ('kr_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='인형 이름(한국어)')),
                ('rank', models.CharField(blank=True, choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=1, null=True, verbose_name='인형 등급')),
                ('type', models.CharField(blank=True, choices=[('hg', 'HG'), ('smg', 'SMG'), ('rf', 'RF'), ('ar', 'AR'), ('mg', 'MG'), ('sg', 'SG')], max_length=3, null=True, verbose_name='인형 유형')),
                ('illust', models.CharField(blank=True, max_length=50, null=True, verbose_name='일러스트레이터')),
                ('voice', models.CharField(blank=True, max_length=50, null=True, verbose_name='성우')),
                ('build_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='제조 시간')),
                ('is_upgrade', models.BooleanField(blank=True, default=False, verbose_name='개조')),
            ],
        ),
        migrations.CreateModel(
            name='DollDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_field', models.CharField(blank=True, max_length=30, verbose_name='Drop Fields')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_drop', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollEffectGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_pw', models.PositiveSmallIntegerField()),
                ('effect_dr', models.PositiveSmallIntegerField()),
                ('effect_cd', models.PositiveSmallIntegerField()),
                ('effect_ic', models.PositiveSmallIntegerField()),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_effect_grid', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollEffectPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_pos', models.PositiveSmallIntegerField()),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_effect_pos', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollEffectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(blank=True, max_length=50)),
                ('effect_center', models.PositiveSmallIntegerField()),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_effect_type', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSDImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_sd_wait_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 기본 일러스트')),
                ('doll_sd_attack_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 공격 일러스트')),
                ('doll_sd_die_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 파손 일러스트')),
                ('doll_sd_move_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 이동 일러스트')),
                ('doll_sd_victory1_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 승리1 일러스트')),
                ('doll_sd_victory2_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 승리2 일러스트')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_sd', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_skill', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollSkinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_skin_name', models.CharField(blank=True, max_length=50, verbose_name='스킨 이름')),
                ('doll_skin_story', models.TextField(blank=True, max_length=255, verbose_name='스킨 스토리')),
                ('doll_sd_skin', models.ImageField(blank=True, upload_to='doll_sd_skins', verbose_name='스킨 SD 일러스트')),
                ('doll_default_skin', models.ImageField(blank=True, upload_to='doll_default_skins', verbose_name='스킨 기본 일러스트')),
                ('doll_damage_skin', models.ImageField(blank=True, upload_to='doll_damage_skins', verbose_name='스킨 파손 일러트스')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_skins', to='tactical_dolls.Doll')),
            ],
        ),
        migrations.CreateModel(
            name='DollStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.PositiveSmallIntegerField(blank=True, verbose_name='장갑')),
                ('dodge', models.PositiveSmallIntegerField(blank=True, verbose_name='회피')),
                ('hit', models.PositiveSmallIntegerField(blank=True, verbose_name='명중')),
                ('hp', models.PositiveSmallIntegerField(blank=True, verbose_name='체력')),
                ('pow', models.PositiveSmallIntegerField(blank=True, verbose_name='화력')),
                ('range', models.PositiveSmallIntegerField(blank=True, verbose_name='사거리(철혈)')),
                ('rate', models.PositiveSmallIntegerField(blank=True, verbose_name='사속')),
                ('shield', models.PositiveSmallIntegerField(blank=True, verbose_name='보호막(철혈)')),
                ('speed', models.PositiveSmallIntegerField(blank=True, verbose_name='이동속도')),
                ('crit', models.PositiveSmallIntegerField(blank=True, verbose_name='크리티컬 확률(%)')),
                ('critdmg', models.PositiveSmallIntegerField(blank=True, verbose_name='크리티컬 데미지 추가 증가량(%)')),
                ('armor_piercing', models.PositiveSmallIntegerField(blank=True, verbose_name='장갑 관통')),
                ('night_view', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='야간 명중률(%)')),
                ('cool_down', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='쿨타임 감소(%)')),
                ('bullet', models.PositiveSmallIntegerField(blank=True, verbose_name='장탄 수')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doll_status', to='tactical_dolls.Doll')),
            ],
        ),
    ]
