# Generated by Django 2.1.1 on 2018-09-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_no', models.PositiveIntegerField(verbose_name='인형 품번')),
                ('doll_name', models.CharField(max_length=50, verbose_name='인형 이름')),
                ('doll_type', models.CharField(choices=[('HG', 'HG'), ('SM', 'SMG'), ('RF', 'RF'), ('AR', 'AR'), ('MG', 'MG'), ('SG', 'SG')], max_length=2, verbose_name='인형 유형')),
                ('doll_rating', models.CharField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=1, verbose_name='인형 등급')),
                ('doll_thumbnail_image', models.ImageField(upload_to='doll_thumbnail_images', verbose_name='아이콘 일러스트')),
                ('doll_default_image', models.ImageField(upload_to='doll_default_images', verbose_name='기본 일러스트')),
                ('doll_damage_image', models.ImageField(upload_to='doll_damage_images', verbose_name='파손 일러스트')),
                ('doll_Introduce', models.TextField(max_length=255, verbose_name='소개')),
                ('doll_cv', models.CharField(blank=True, max_length=50, verbose_name='성우')),
                ('doll_illustrator_creator', models.CharField(blank=True, max_length=50, verbose_name='일러스트레이터')),
                ('doll_manufacturing_time', models.CharField(max_length=20, verbose_name='제조 시간')),
                ('doll_is_upgrade', models.BooleanField(default=False, verbose_name='개조')),
                ('doll_fp', models.PositiveSmallIntegerField(verbose_name='화력')),
                ('doll_acc', models.PositiveSmallIntegerField(verbose_name='명중')),
                ('doll_eva', models.PositiveSmallIntegerField(verbose_name='회피')),
                ('doll_rof', models.PositiveSmallIntegerField(verbose_name='사속')),
                ('doll_hp', models.PositiveSmallIntegerField(verbose_name='체력')),
                ('doll_growth', models.PositiveSmallIntegerField(verbose_name='성장')),
            ],
        ),
        migrations.CreateModel(
            name='DollsDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_drop_field', models.CharField(blank=True, max_length=30, verbose_name='Drop Fields')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_drop', to='tactical_dolls.Dolls')),
            ],
        ),
        migrations.CreateModel(
            name='DollsSDImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_sd_wait_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 기본 일러스트')),
                ('doll_sd_attack_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 공격 일러스트')),
                ('doll_sd_die_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 파손 일러스트')),
                ('doll_sd_move_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 이동 일러스트')),
                ('doll_sd_victory1_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 승리1 일러스트')),
                ('doll_sd_victory2_image', models.ImageField(blank=True, upload_to='doll_sd_image', verbose_name='SD 승리2 일러스트')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_sd', to='tactical_dolls.Dolls')),
            ],
        ),
        migrations.CreateModel(
            name='DollsSkinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_skin_name', models.CharField(blank=True, max_length=50, verbose_name='스킨 이름')),
                ('doll_skin_story', models.TextField(blank=True, max_length=255, verbose_name='스킨 스토리')),
                ('doll_sd_skin', models.ImageField(upload_to='doll_sd_skins', verbose_name='스킨 SD 일러스트')),
                ('doll_default_skin', models.ImageField(blank=True, upload_to='doll_default_skins', verbose_name='스킨 기본 일러스트')),
                ('doll_damage_skin', models.ImageField(blank=True, upload_to='doll_damage_skins', verbose_name='스킨 파손 일러트스')),
                ('doll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doll_skins', to='tactical_dolls.Dolls')),
            ],
        ),
    ]
