# Generated by Django 2.1.1 on 2018-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='skill01_codename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doll',
            name='skill02_codename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
