# Generated by Django 2.1.1 on 2018-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolls',
            name='doll_cv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='성우'),
        ),
        migrations.AlterField(
            model_name='dolls',
            name='doll_illustrator_creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='일러스트레이터'),
        ),
    ]
