# Generated by Django 2.1.2 on 2018-10-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollstatus',
            name='night_view',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
