# Generated by Django 2.1.1 on 2018-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollskill01',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='doll_skill_images'),
        ),
        migrations.AddField(
            model_name='dollskill02',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='doll_skill_images'),
        ),
    ]
