# Generated by Django 2.1.2 on 2018-10-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0002_dollstatus_night_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollstatus',
            name='critical_harm_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
