# Generated by Django 2.1.2 on 2018-10-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0002_auto_20181025_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollskill01',
            name='cool_down_type',
            field=models.CharField(blank=True, choices=[('frame', 'frame'), ('turn', 'turn')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dollskill02',
            name='cool_down_type',
            field=models.CharField(blank=True, choices=[('frame', 'frame'), ('turn', 'turn')], max_length=50, null=True),
        ),
    ]
