# Generated by Django 2.1.1 on 2018-09-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0002_auto_20180914_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolleffect',
            name='effect_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
