# Generated by Django 2.1.1 on 2018-09-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0002_auto_20180925_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollstatus',
            name='armor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
