# Generated by Django 2.1.1 on 2018-09-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0002_auto_20180913_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolls',
            name='doll_krname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='인형 이름(한국어)'),
        ),
    ]
