# Generated by Django 2.1.1 on 2018-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0003_auto_20180913_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolls',
            name='doll_cooldown',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='쿨타임 감소(%)'),
        ),
        migrations.AddField(
            model_name='dolls',
            name='doll_nightview',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='야간 명중률(%)'),
        ),
    ]
