# Generated by Django 2.1.1 on 2018-09-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0003_auto_20180919_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dolleffectgrid',
            old_name='colldown',
            new_name='cooldown',
        ),
    ]
