# Generated by Django 2.1.1 on 2018-09-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_dolls', '0005_auto_20180920_1739'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doll',
            managers=[
            ],
        ),
    ]
