# Generated by Django 2.1.2 on 2018-10-29 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('code_name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='equip_image')),
                ('category', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('exclusive_rate', models.PositiveIntegerField()),
                ('max_level', models.PositiveSmallIntegerField()),
                ('build_time', models.PositiveIntegerField()),
                ('pow', models.SmallIntegerField()),
                ('hit', models.SmallIntegerField()),
                ('rate', models.SmallIntegerField()),
                ('dodge', models.SmallIntegerField()),
                ('armor', models.SmallIntegerField()),
                ('bullet', models.SmallIntegerField()),
                ('critical_percent', models.SmallIntegerField()),
                ('critical_harm_rate', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
                ('night_view', models.SmallIntegerField()),
                ('armor_piercing', models.SmallIntegerField()),
                ('private_field', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None), blank=True, null=True, size=None)),
            ],
        ),
    ]
