# Generated by Django 2.1.2 on 2018-10-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('code_name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('exclusive_rate', models.PositiveIntegerField()),
                ('max_level', models.PositiveSmallIntegerField()),
                ('build_time', models.PositiveIntegerField()),
                ('is_private', models.BooleanField(default=False)),
                ('pow', models.SmallIntegerField()),
                ('hit', models.SmallIntegerField()),
                ('rate', models.SmallIntegerField()),
                ('dodge', models.SmallIntegerField()),
                ('armor', models.SmallIntegerField()),
                ('bullet', models.SmallIntegerField()),
                ('critical_percent', models.SmallIntegerField()),
                ('critical_harm_rate', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
                ('night_view', models.SmallIntegerField()),
                ('armor_piercing', models.SmallIntegerField()),
                ('private_field', models.ManyToManyField(blank=True, related_name='private_equipment', to='equip.Equip')),
            ],
        ),
        migrations.CreateModel(
            name='EquipPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_equip_apply_doll', to='doll.Doll')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_equip_module', to='equip.Equip')),
            ],
        ),
    ]
