# Generated by Django 2.1.2 on 2018-10-28 06:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipprivate',
            name='doll',
        ),
        migrations.RemoveField(
            model_name='equipprivate',
            name='equip',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='private_field',
        ),
        migrations.AddField(
            model_name='equip',
            name='private_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='EquipPrivate',
        ),
    ]
