# Generated by Django 2.1.2 on 2018-10-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_equips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollEquipFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_doll_id', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dollequip',
            name='equip_image',
            field=models.ImageField(blank=True, null=True, upload_to='equip_image'),
        ),
        migrations.AddField(
            model_name='dollequip',
            name='is_private',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dollequipfit',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doll_equip_fit', to='tactical_equips.DollEquip'),
        ),
    ]
