# Generated by Django 2.1.2 on 2018-10-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_equips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollequip',
            name='build_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
