# Generated by Django 2.1.2 on 2018-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_equips', '0002_auto_20181025_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollequipfit',
            name='fit_doll_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
