# Generated by Django 2.1.2 on 2018-10-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical_equips', '0005_auto_20181025_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollequipstatus',
            name='armor',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='armor_piercing',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='bullet',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='critical_harm_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='critical_percent',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='dodge',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='hit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='night_view',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='pow',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dollequipstatus',
            name='speed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
